<a href="https://colab.research.google.com/github/salonisngh/cognitive-computing/blob/main/Assignment_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Q.1 Write a program to create a NumPy 1D-array with 5 elements and perform basic
operations like:

a) Addition of 2 in all the element
b) Multiply 3 with all the elements
c) Divide every element by 2

In [ ]:
import numpy as np;
arr=np.array([1,2,3,4,5]);

print(arr+2);
print(arr*3);
print(arr/2);



[1 2 3 4 5]
[3 4 5 6 7]
[ 3  6  9 12 15]
[0.5 1.  1.5 2.  2.5]


Q.2 Questions on Basic NumPy Array:

a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])


In [ ]:
import numpy as np;
arr=np.array([1,2,3,6,4,5])
print ((arr[::-1]))

[5 4 6 3 2 1]


b) Find the most frequent value and their indice(s) in the following arrays:

i. x = np.array([1,2,3,4,5,1,2,1,1,1])

ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

In [ ]:
import numpy as np;
def most_frequent_with_indices(arr):
    counts = np.bincount(arr)
    max_count = np.max(counts)
    most_frequent_values = np.where(counts == max_count)[0]
    indices_dict = {value: np.where(arr == value)[0] for value in most_frequent_values}
    return most_frequent_values, indices_dict

x=np.array([1,2,3,4,5,1,2,1,1,1])
y=np.array([1,1,1,2,3,4,2,4,3,3])
frequent_x,indices_x= most_frequent_with_indices(x)
frequent_y,indices_y= most_frequent_with_indices(y)
print(f"Most frequent in x: {frequent_x} at indice(s) {indices_x}")
print(f"Most frequent in y: {frequent_y} at indice(s) {indices_y}")



Most frequent in x: [1] at indice(s) {1: array([0, 5, 7, 8, 9])}
Most frequent in y: [1 3] at indice(s) {1: array([0, 1, 2]), 3: array([4, 8, 9])}


Q.3 For the given 2-D array arr=np.array([10, 20, 30], [40, 50, 60], [70, 80, 90]), access
elements using row and column indices as follows:

a) Access 1st row, 2nd column

b) Access 3rd row, 1st column

In [ ]:
import numpy as np;

arr=np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]]);

print(arr[0,1]);
print(arr[2,0])

20
70


Q.4 Write program to create an 1-D NumPy array named (Your Name) with evenly
spaced 25 numbers from 10 to 100 using linspace(). Print the dimensions of the array,
shape, total elements, the data type of each element and total number of bytes consumed
by the array. Find the transpose of this array using reshape() attribute. Can we do the same
with T attribute?

In [ ]:
import numpy as np;

singh= np.linspace(10,100,25);
print("ARRAY: ", singh)
print("DIMENSION: ", singh.ndim)
print( "SHAPE: ", singh.shape)
print("TOTAL ELEMENTS: ", singh.size)
print("DATA TYPE:", singh.dtype)
print("TOTAL NO. OF BYTES:", singh.nbytes)


TransposeR=singh.reshape(25,1)
print("Using reshape, Transpose: ")
print(TransposeR)

TransposeT=singh.T
print("Using T attribute, Transpose: ")
print(TransposeT)

print("Conclusion: No we Can't use T attribute.")

ARRAY:  [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
DIMENSION:  1
SHAPE:  (25,)
TOTAL ELEMENTS:  25
DATA TYPE: float64
TOTAL NO. OF BYTES: 200
Using reshape, Transpose: 
[[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
Using T attribute, Transpose: 
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Conclusion: No we Can't use T attribute.


Q5

In [2]:
import numpy as np;

ucs420= np.array([[10,20,30,40],
                  [50,60,70,80],
                  [90,15,20,35]])
print(f"Orginal:\n{ucs420}")
print("mean: ",np.mean(ucs420))
print("median: ",np.median(ucs420))
print("max: ",np.max(ucs420))
print("min: ",np.min(ucs420))
print("unique elements: ",np.unique(ucs420))

reshaped_ucs420= ucs420.reshape(4,3)
print(f"Reshaped:\n{reshaped_ucs420}")
resized_ucs420 = np.resize(ucs420,(2,3))
print(f"Resized:\n{resized_ucs420}")


Orginal:
[[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]
mean:  43.333333333333336
median:  37.5
max:  90
min:  10
unique elements:  [10 15 20 30 35 40 50 60 70 80 90]
Reshaped:
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
Resized:
[[10 20 30]
 [40 50 60]]
